<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD -->
<!DOCTYPE recepty [
    <!ELEMENT recepty (recept)>
    <!ELEMENT recept (informace, suroviny, postup)>
    <!ELEMENT informace (autor, datum, nazev, kategorie)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT datum (#PCDATA)>
    <!ELEMENT nazev (#PCDATA)>
    <!ELEMENT kategorie (rumova, jemny)>
    <!ELEMENT jemny EMPTY>
    <!ELEMENT rumova EMPTY>
    <!ELEMENT suroviny (surovina)>
    <!ELEMENT surovina (#PCDATA)>
    <!ELEMENT postup (krok)>
    <!ELEMENT krok (#PCDATA)>
    <!ATTLIST surovina odkaz CDATA >
]>
<!-- Informations -->
<recepty>
  <recept>
    <informace>
      <autor>Josef Nov√°k</autor>
        <datum>27.11.2021</datum>
        <nazev>Cuba Libre</nazev>
        <kategorie>
          <rumova/>
          <jemny/>
        </kategorie>
    </informace>
    <suroviny>
      <surovina odkaz="http://drinkshop.cz">Coca-Cola</surovina>
      <surovina>Rum</surovina>
      <surovina odkaz="http://globus.cz/limetka">Limetka</surovina>
    </suroviny>
    <postup>
      <krok>Nalij Rum a colu</krok>
      <krok>Zamichej a pridej limetku</krok>
    </postup>
  </recept>
</recepty>